version: "3"

services:
  ckan:
    image: ghcr.io/gsa/catalog.data.gov:latest
    command: ./ckan_setup.sh ckan run -H 0.0.0.0
    env_file: .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - .:/app

  db:
    env_file:
      - .env
    image: ghcr.io/gsa/catalog.data.gov.db:latest
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    image: ghcr.io/gsa/catalog.data.gov.solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    image: redis:alpine

  nginx:
    image: nginx
    links:
      - ckan
    ports:
      - "8443:443"
    volumes:
      - ./nginx:/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/ckan.conf

  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html
      - ./tests/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  ckan_storage:
  pg_data:
  solr_data:
