version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: make build
      - run:
          name: Archive Docker image
          command: docker save -o image.tar datagov/catalog.data.gov:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
      - run: 
          name: lint and test
          command: |
            docker-compose up -d
            make lint-all
            make quick-bat-test
    
  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests 
          command: make test-import-tool
  
  start_ckan_28:
    docker:
      # this image should be used in all extensions 
      - image: cimg/base:stable-18.04
    steps:
      - checkout
      - run:
          name: Start CKAN 2.8
          command: |
            cp ckan/test-catalog-next.ini tools/ci-scripts/
            cd tools/ci-scripts
            ./circleci-build-catalog-next.bash
  
  docker_publish:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Tag and publish image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push datagov/catalog.data.gov:latest

      
workflows:
  version: 2
  commit:
    jobs:
      - start_ckan_28
      - deploy-sandbox:
          requires:
            - test
          filters:
            branches:
              only: master
      - test_importer
      - test
      - docker_publish:
          requires:
            - test
          filters:
            branches:
              only: master
