version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make build ci
      - run: make test

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_extension:
    machine: true
    steps:
      - checkout
      - run: make up
      - run: docker-compose exec ckan bash -c "cd src_extensions/ckanext-catalogdatagov && nosetests -v -s --with-pylons=test.ini"

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master
      - test_extension
