version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make build ci
      - run: make test
      - run: make test-catalog-ext

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: Trigger Jenkins deploy
          command: bin/jenkins_build deploy-ci-app-catalog-next
  
  test_importer: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: tests 
          command: | 
            cd tools/harvest_source_import
            pip install --upgrade pip 
            pip install -r dev-requirements.txt
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            python -m pytest --vcr-record=none tests/

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master
      - test_importer
