---
name: commit

on:
  push:


jobs:
  test-ckan-28:
    name: lint and test CKAN 2.8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ckan28
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: Archive Catalog Docker image
        run: docker save -o image-catalog-28.tar datagov/catalog.data.gov:latest
      - name: Archive Solr Docker image
        run: docker save -o image-solr-28.tar datagov/catalog.data.gov.solr:latest
      - name: Archive DB Docker image
        run: docker save -o image-db-28.tar datagov/catalog.data.gov.db:latest
      - uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: |
            image-catalog-28.tar
            image-solr-28.tar
            image-db-28.tar
          if-no-files-found: error
      - name: lint and test CKAN 2.8
        run: |
          docker-compose up -d
          make lint-all
          make quick-bat-test

  test-ckan-29:
    name: lint and test CKAN 2.9
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ckan29
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: Archive Catalog Docker image
        run: docker save -o image-catalog-29.tar datagov/catalog.data.gov:ckan29
      - name: Archive Solr Docker image
        run: docker save -o image-solr-29.tar datagov/catalog.data.gov.solr:ckan29
      - name: Archive DB Docker image
        run: docker save -o image-db-29.tar datagov/catalog.data.gov.db:ckan29
      - uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: |
            image-catalog-29.tar
            image-solr-29.tar
            image-db-29.tar
          if-no-files-found: error
      - name: lint and test CKAN 2.9
        run: |
          docker-compose up -d
          make lint-all
          make quick-bat-test

  test_importer:
    name: test importer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ckan28
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: test_importer
        run: make test-import-tool

  vendor:
    name: vendor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: vendor dependencies
        run: ./vendor-requirements.sh
      - uses: actions/upload-artifact@v2
        with:
          name: python-vendored
          path: vendor/
          if-no-files-found: error

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    name: deploy (development)
    environment: development
    runs-on: ubuntu-latest
    needs:
      - test-ckan-28
      - vendor
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push catalog --vars-file vars.development.yml --strategy rolling
          org: gsa-datagov
          space: development
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          curl --fail --silent https://catalog-dev-datagov.app.cloud.gov/api/action/status_show?$(date +%s)

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    name: deploy (staging)
    environment: staging
    runs-on: ubuntu-latest
    needs:
      - test-ckan-28
      - vendor
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push catalog --vars-file vars.staging.yml --strategy rolling
          org: gsa-datagov
          space: staging
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          curl --fail --silent https://catalog-stage-datagov.app.cloud.gov/api/action/status_show?$(date +%s)

  deploy-production:
    if: github.ref == 'refs/heads/main'
    name: deploy (production)
    environment: production
    runs-on: ubuntu-latest
    needs:
      - deploy-staging
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-vendored
          path: vendor
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push catalog --vars-file vars.production.yml --strategy rolling
          org: gsa-datagov
          space: prod
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 10
          curl --fail --silent https://catalog-prod-datagov.app.cloud.gov/api/action/status_show?$(date +%s)
